### ISSUE TITLE
Installing Symfony Messenger for the first time will render an error

### ISSUE THREAD

**Issue by gabiudrescu** [Setono/SyliusFeedPlugin#17]
This should be added to the readme install steps:

```
(optional) If you don't use symfony/messenger component yet, it is required to configure one of the message buses as a default bus:

framework:
    messenger:
        default_bus: setono_sylius_feed.command_bus
```

inspired by this: https://github.com/Sylius/InvoicingPlugin/pull/164
