### ISSUE TITLE
LiipImagine Cache Resolve wrong domain url using command

### ISSUE THREAD

**Issue by Loocos** [Setono/SyliusFeedPlugin#40]
Hello guys,

When using the `php bin/console setono:sylius-feed:process` command by crontab, the product image link return `http://localhost/media/...`
After that, either Facebook either Google will not be able to sync the products catalog.

**Comment by loevgaard** [comment]
I am 99,9% sure it's taken from the host on the channel :)

**Comment by loevgaard** [comment]
Also it's a good idea to have this in your `config/services.yaml`:

```yaml
parameters:
    # ...

    router.request_context.host: '%env(REQUEST_CONTEXT_DEFAULT_HOST)%'
    router.request_context.scheme: '%env(REQUEST_CONTEXT_DEFAULT_SCHEME)%'

    # ...
```
